"""baseline

Revision ID: 1060e29bf8f7
Revises: aa23d2985828
Create Date: 2025-08-29 11:21:26.780831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1060e29bf8f7'
down_revision = 'aa23d2985828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('reports', 'ngo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'ngo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###
